version: "2"

services:
  rabbitmq:
    extends:
      file: rabbitmq/docker-compose.yml
      service: rabbitmq

  producer-rabbitmq:
    extends:
      file: producer_rabbitmq/docker-compose.yml
      service: producer

  consumer-rabbitmq:
    extends:
      file: consumer_rabbitmq/docker-compose.yml
      service: consumer

  zookeeper:
    extends:
      file: kafka/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: kafka/docker-compose.yml
      service: kafka

  kafka-manager:
    extends:
      file: kafka/docker-compose.yml
      service: manager

  kafka-kafdrop:
    extends:
      file: kafka/docker-compose.yml
      service: kafdrop

  kafka-trifecta:
    extends:
      file: kafka/docker-compose.yml
      service: trifecta

  producer-kafka:
    extends:
      file: producer_kafka/docker-compose.yml
      service: producer

  consumer-kafka:
    extends:
      file: consumer_kafka/docker-compose.yml
      service: consumer

  kafka-redpanda:
    extends:
      file: kafka/docker-compose.yml
      service: redpanda

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  producer-rails-karafka:
    extends:
      file: producer_rails_karafka/docker-compose.yml
      service: producer

  consumer-rails-karafka:
    extends:
      file: consumer_rails_karafka/docker-compose.yml
      service: consumer