version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-manager:
    image: hlebalbau/kafka-manager
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=secret
    depends_on:
      - zookeeper
      - kafka
  rabbitmq:
    image: rabbitmq:3.11.5-management
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # HTTP management port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  producer_rabbitmq:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby producer.rb"
    volumes:
      - ./producer_rabbitmq:/app
    depends_on:
      - rabbitmq
  consumer_rabbitmq:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby consumer.rb"
    volumes:
      - ./consumer_rabbitmq:/app
    depends_on:
      - rabbitmq
  producer_kafka:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby producer.rb"
    volumes:
      - ./producer_kafka:/app
    depends_on:
      - kafka
  consumer_kafka:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby consumer.rb"
    volumes:
      - ./consumer_kafka:/app
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
