version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rabbitmq:
    image: rabbitmq:3.11.5-management
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # HTTP management port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  producer:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby producer.rb"
    volumes:
      - ./producer:/app
    depends_on:
      - rabbitmq
      - kafka
  consumer:
    image: ruby
    command: bash -c "cd /app && bundle install && bundle exec ruby consumer.rb"
    volumes:
      - ./consumer:/app
    depends_on:
      - rabbitmq
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
