services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    user: "1042"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  manager:
    image: hlebalbau/kafka-manager
    ports:
      - "9000:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=secret
    depends_on:
      - kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9010:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka

  trifecta:
    image: chatu/trifecta
    ports:
      - "8888:8888"
    environment:
      - ZOOKEEPERS=zookeeper:2181
    depends_on:
      - kafka

  redpanda:
    image: docker.redpanda.com/vectorized/console:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
